### PR TITLE
chore: add close-pull-request.yml

### PR DESCRIPTION
**Pull request by kenjis**

### CODE REVIEW

**Review by MGatner — APPROVED** [review]
👍

**Comment by paulbalandan** [comment]
This is already in the main repo, but not being deployed here during release? It seems to be a problem with the deploy script.

**Comment by MGatner** [comment]
The User Guide deploy script only builds the HTML & ePub and updates them: https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/scripts/deploy-userguide

**Comment by paulbalandan** [comment]
Yes, but should it also copy repo-specific files?
https://github.com/codeigniter4/CodeIgniter4/blob/6eaa945aa6f6f2a21f823284206a11911bda553d/.github/scripts/deploy-framework#L29-L32

**Comment by kenjis** [comment]
@paulbalandan I got what you mean. I did not understand "This is already in the main repo".

**Comment by kenjis** [comment]
Yes, `Copy repo-specific files` is missing only in [deploy-userguide](https://github.com/codeigniter4/CodeIgniter4/blob/develop/.github/scripts/deploy-userguide).

**Comment by paulbalandan** [comment]
> @paulbalandan I got what you mean. I did not understand "This is already in the main repo".

I mean the [file](https://github.com/codeigniter4/CodeIgniter4/blob/develop/admin/userguide/.github/workflows/close-pull-request.yml) is already there but not copied here.

**Comment by kenjis** [comment]
It seems now files in [admin/userguide](https://github.com/codeigniter4/CodeIgniter4/tree/develop/admin/userguide) is not used at all.

This repo has its own https://github.com/codeigniter4/userguide/blob/master/.github/workflows/deploy.yml and 
https://github.com/codeigniter4/userguide/blob/master/.github/scripts/deploy

**Comment by kenjis** [comment]
Which will we go?

1. remove [admin/userguide](https://github.com/codeigniter4/CodeIgniter4/tree/develop/admin/userguide)
2. move all repo-specific files to [admin/userguide](https://github.com/codeigniter4/CodeIgniter4/tree/develop/admin/userguide)

**Comment by kenjis** [comment]
@paulbalandan Your opinion?

**Comment by paulbalandan** [comment]
For me, i would go for 2 as we have already the scripts available to manage the process. Just need a little tweaking. If we are to make this repo "functional", i think that would be more to maintain.

**Comment by kenjis** [comment]
This repository is for publishing and archiving the documentation.

The README says "This is a read-only repository used to publish the user guide for the current release."
https://github.com/codeigniter4/userguide/blob/master/README.md

The original intent is read-only. Then it is better not to hold the repo-specific contents.

I would like to go for 2.

**Comment by MGatner** [comment]
Let's go with 2 then.

**Comment by kenjis** [comment]
I sent https://github.com/codeigniter4/CodeIgniter4/pull/7059

**Comment by kenjis** [comment]
Closed by https://github.com/codeigniter4/CodeIgniter4/pull/7059

**Pull request closed without merging**
