### PR TITLE
rename function name and adding close parentheses 

### PR DESCRIPTION
**Pull request by zawaruddin**
- Rename `cache_info()` function with `getCacheInfo()`.
- Adding close parentheses, so the example code not error while copy/paste in the editor.

### CODE REVIEW

**Comment by totoprayogo1916** [comment]
Make a Pull Request on the main repository

**Comment by zawaruddin** [comment]
so, this is not main repository for CI4 user guide?

**Comment by totoprayogo1916** [comment]
you can found here: https://github.com/codeigniter4/CodeIgniter4/tree/develop/user_guide_src

**Comment by totoprayogo1916** [comment]
for more information, please read https://codeigniter4.github.io/userguide/installation/repositories.html

**Comment by zawaruddin** [comment]
> 
> 
> you can found here: https://github.com/codeigniter4/CodeIgniter4/tree/develop/user_guide_src

Ok, i'll pull request in here.

**Comment by zawaruddin** [comment]
btw, thank you for your notification....

**Pull request closed without merging**
